# Generated by Django 2.2.16 on 2021-06-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamParser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='default',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='icon_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
