# Generated by Django 2.2.16 on 2021-06-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamParser', '0002_auto_20210629_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='icon_url',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
